Fix: searchterm maxlength
thorsten/phpMyFAQ pull request #2643
Opened 2023-09-16 04:08 UTC by sasamario

A DB error occurs when a keyword search is performed on a string of more than 255 characters.
This is because the limit of the searchterm column in the "faqsearches" table is exceeded.

Therefore, the following modifications have been made.
・Add "maxlength" to the attribute of the keyword input column.
・When acquiring the input value, the maximum length is 255 characters from the beginning.

2023-09-16 10:45 UTC, thorsten requested changes
Looks good except of the usage of `mb_substr()`

2023-09-16 10:45 UTC, thorsten commented on phpmyfaq/search.php
> +$inputSearchTerm = mb_substr(Filter::filterVar($request->query->get('search'), FILTER_SANITIZE_SPECIAL_CHARS), 0, 255);
You can use `String::substr()` instead of `mb_substr()` here

2023-09-16 10:45 UTC, thorsten commented on phpmyfaq/search.php
> +$searchTerm = mb_substr(Filter::filterVar($request->request->get('search'), FILTER_SANITIZE_SPECIAL_CHARS), 0, 255);
You can use `String::substr()` instead of `mb_substr()` here

2023-09-17 02:13 UTC, sasamario commented
Thank you for your review.
We have corrected the problem, please check back.

2023-09-17 05:20 UTC, merged

2023-09-17 05:20 UTC, thorsten commented
Thanks!