Add experimental feature to import record data from csv file
thorsten/phpMyFAQ pull request #2790
Opened 2024-01-05 19:03 UTC by modelrailroader

#2163

2024-01-06 09:18 UTC, thorsten requested changes

2024-01-06 09:18 UTC, thorsten commented on phpmyfaq/admin/index.php
> +            ->setLanguagesDir(PMF_TRANSLATION_DIR)
The indent here is wrong :-)

2024-01-06 09:18 UTC, thorsten commented on phpmyfaq/src/phpMyFAQ/Faq/FaqImport.php
> +    {
We need to validate the CSV

2024-01-06 09:18 UTC, thorsten commented on phpmyfaq/admin/csv.import.php
> +        foreach ($csvData as $record) {
This logic should be in the FaqImport class as well

2024-01-12 19:25 UTC, modelrailroader commented
Close due to the necessary to create a new PR #2800

2024-01-12 19:25 UTC, closed without merging