Edit forms
thorsten/phpMyFAQ pull request #2887
Opened 2024-03-21 15:04 UTC by modelrailroader

2024-03-21 15:04 UTC, modelrailroader commented
#2886

2024-03-22 16:30 UTC, thorsten requested changes

2024-03-22 16:30 UTC, thorsten commented on phpmyfaq/src/phpMyFAQ/Setup/Update.php
> +        $forms = new Forms($this->configuration);
Adding the new table is missing?

2024-03-22 16:30 UTC, thorsten commented on phpmyfaq/src/phpMyFAQ/Setup/Update.php
> +        $forms = new Forms($this->configuration);
The new permissions are not added?

2024-03-28 17:15 UTC, thorsten approved these changes

2024-03-28 18:08 UTC, merged