Adapted add-faq-form to #2886
thorsten/phpMyFAQ pull request #2980
Opened 2024-06-04 17:52 UTC by modelrailroader

One part of #2886 and minor changes in design and programming

2024-06-04 17:59 UTC, modelrailroader commented on phpmyfaq/admin/assets/src/api/forms.js
> +        option.innerHTML = element.getAttribute('data-pmf-langname');
Done.

2024-06-05 07:21 UTC, thorsten requested changes

2024-06-05 07:21 UTC, thorsten commented on phpmyfaq/assets/templates/admin/configuration/forms.translations.twig
> +                    data-pmf-csrf="{{ csrfTokenEditTranslation }}" style="cursor: pointer">
Could we move that into a SCSS file instead of using inline CSS?

2024-06-05 07:21 UTC, thorsten commented on phpmyfaq/assets/templates/admin/configuration/forms.translations.twig
> +                    style="cursor: pointer">
same here, we should avoid inline CSS

2024-06-05 07:21 UTC, thorsten commented on phpmyfaq/src/phpMyFAQ/Faq/MetaData.php
> +        $faqPermission->add(Permission::USER, $this->categories, $userPermissions);
Is this change correct?

2024-06-05 16:04 UTC, modelrailroader commented
I removed the inline css.

2024-06-07 04:32 UTC, merged