Tooltips & Share via WhatsApp
thorsten/phpMyFAQ pull request #3071
Opened 2024-07-02 19:22 UTC by modelrailroader

#2969

2024-07-02 19:26 UTC, modelrailroader commented
This test didn't faile because of my changes

2024-07-03 05:27 UTC, thorsten requested changes

2024-07-03 05:27 UTC, thorsten commented on phpmyfaq/src/phpMyFAQ/Helper/FaqHelper.php
> +    public function renderSendToFriendViaWhatsapp(string $url): string
Why not add it directly into the Twig template as plain HTML?

2024-07-03 19:00 UTC, modelrailroader commented
This finallly finished. :D

2024-07-03 19:59 UTC, thorsten requested changes

2024-07-03 19:59 UTC, thorsten commented on phpmyfaq/.htaccess
> +    RewriteRule ^api/(autocomplete|bookmark/remove/([0-9]+)|bookmark/add/([0-9]+)|user/data/update|user/password/update|user/request-removal|user/remove-twofactor|contact|voting|register|captcha|shar
- Please don't add the ID in an API URL
- rename "remove" to "delete"
- rename "add" to "create"

2024-07-03 19:59 UTC, thorsten commented on phpmyfaq/admin/assets/src/utils/utils.js
> +  const tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
You can use an arrow function here.

2024-07-03 19:59 UTC, thorsten commented on phpmyfaq/assets/src/api/bookmarks.js
> +    const response = await fetch(`api/bookmark/add/${faqId}`, {
- Please send the ID via body
- Rename "add" to "create"

2024-07-03 19:59 UTC, thorsten commented on phpmyfaq/assets/src/api/bookmarks.js
> +    const response = await fetch(`api/bookmark/remove/${faqId}`, {
- please move the ID to the body
- please rename "remove" to "delete"

2024-07-03 19:59 UTC, thorsten commented on phpmyfaq/assets/src/user/bookmarks.js
> +export const handleBookmarks = () => {
wouldn't be "handleDeleteBookmarks" better?

2024-07-03 19:59 UTC, thorsten commented on phpmyfaq/src/phpMyFAQ/Controller/Frontend/BookmarkController.php
> +    public function remove(Request $request): JsonResponse
Please use "delete" instead of "remove"

2024-07-03 19:59 UTC, thorsten commented on phpmyfaq/src/phpMyFAQ/Controller/Frontend/BookmarkController.php
> +    public function add(Request $request): JsonResponse
please rename from "add" to "create"

2024-07-04 14:35 UTC, modelrailroader commented
Closes #3083

2024-07-05 05:27 UTC, merged